У завданнях 1-4. Вам наданий простий код на Python, який не відповідає вказівкам PEP8. Ваше завдання — відредагувати код так, аби він відповідав PEP8. Напишіть після редагуванню коду, дотримання яких правил з pep8 ви досягли в відредагованій версі, наприклад
```
- додала пробіли навколо бінарного оператора
- додала два порожні рядки між визначеннями функцій
і тд
```
Також можна зазанчити використані правила коментарями по коду, а не окремим повідомленням.

Відредагований код має виконувати весь той самий функціонал, але бути написаний відповідно до вимог до гарного коду на Python! Не забудьте запустити відредагований код, він має бути робочим.

Завдання 1.

In [1]:
def greet(name):print(f"Hello, {name}")
def add(n1,n2):return n1+n2

x = 5;y = 3
display(greet("John"),add(x,y))

Hello, John

None

8

In [12]:
def greet(name):
  print(f"Hello, {name}")


def add(n1, n2):
  return(x + y)


x = 5
y = 3

display (greet('John'), add(x, y))

#додала пробіли після коми
#між функціями 2 порожні рядки
#відступи 4 пробіли

Hello, John

None

8

Завдання 2.

In [13]:
from math import *
def calcArea(r):return pi*r**2
def calcCircumference(r):return 2*pi*r

radius=5
print("Area:",calcArea(radius),"Circumference:",calcCircumference(radius))

Area: 78.53981633974483 Circumference: 31.41592653589793

In [15]:
from math import pi

def calc_area(radius):
  return pi * radius**2


def calc_circumference(radius):
  return 2 * pi * radius


radius = 5

print(
    'Area:',
    calc_area(radius),
    'Circumference:',
    calc_circumference(radius)
)

#конкретний імпорт
#додала відступи та рядки
#пробіли навколо операторів
#читабельний print

Area: 78.53981633974483 Circumference: 31.41592653589793

Завдання 3.

In [17]:
class animal: pass
class dog(animal):
    def __init__(self,name):
        self.name=name
        self.type='Dog'

In [19]:
class Animal:
  pass


class Dog(Animal):
  def __init__(self,name):
     self.name = name
     self.type = 'Dog'


#додано пробіли навколо "="
#між класами два порожні рядки
#правильні відступи
#назви класів у CapWords

Завдання 4.

In [5]:
list=[1,2,3,4,5]
for i in range(len(list)):print(list[i])

1
2
3
4
5

In [21]:
numbers =[1, 2, 3, 4, 5]

for number in numbers:
  print(number)


#пробіл після коми
#не використовуємо вбудоване list
#зрозумілі змінні
#зрозумілий цикл

1
2
3
4
5

5.У вас є DataFrame df, що представляє результати тестів студентів з математики, англійської мови та історії. Поточний код обчислює середній бал для кожного студента шляхом ітерації за рядками DataFrame за допомогою iterrows().

Ваше завдання полягає в тому, щоб змінити код так, аби уникнути використання iterrows() і замість цього застосувати більш ефективне та читабельне рішення відповідно до правил, озвучених у лекції. Рефакторинг треба зробити лише частині, де рахуються середні, імпорт і визначення датафрейму лишаємо без змін.

In [22]:
import pandas as pd

df = pd.DataFrame({
    'student': ['Alice', 'Bob', 'Charlie', 'David'],
    'math_score': [89, 94, 77, 85],
    'english_score': [92, 88, 79, 85],
    'history_score': [84, 92, 81, 89]
})

In [23]:
averages = []
for _, row in df.iterrows():
    averages.append((row['math_score'] + row['english_score'] + row['history_score']) / 3)

df['average_score'] = averages
averages

[88.33333333333333, 91.33333333333333, 79.0, 86.33333333333333]

In [24]:
df['average_score'] = df[
    ['math_score', 'english_score', 'history_score']
].mean(axis=1)

averages = df['average_score']

averages

0    88.333333
1    91.333333
2    79.000000
3    86.333333
Name: average_score, dtype: float64

6.У Вас є великий DataFrame df, що представляє транзакції продажу в магазині. Цей DataFrame містить понад 1 мільйон рядків і кілька стовпців, зокрема «product_name», «product_category», «product_price» і «transaction_date».

І «product_name», і «product_category» є рядками, що представляють численні, але обмежені унікальні назви продуктів і категорії відповідно.

Напишіть код для ефективного перетворення стовпців «product_name» і «product_category» на категорійний тип для ефективного використання пам’яті.
Спробуйте вирішити це завдання, мінімізуючи використання пам'яті та зберігаючи читабельність коду. Крім того, виміряйте використання пам’яті до та після перетворення, щоб продемонструвати підвищення ефективності.

Порівняйте кількість памʼяті, яку займає наданий набір даних і новий, створений Вами. В лекції був приклад. В скільки разів менше памʼяті займає новий датафрейм?

In [1]:
import pandas as pd
import numpy as np

np.random.seed(0)

products = ['apple', 'banana', 'cherry', 'dates', 'elderberry']
categories = ['fruit', 'fruit', 'fruit', 'fruit', 'fruit']

N_ROWS = 10**6
df = pd.DataFrame({
    'product_name': np.random.choice(products, N_ROWS),
    'product_category': np.random.choice(categories, N_ROWS),
    'product_price': np.random.uniform(1, 10, N_ROWS),
    'transaction_date': pd.date_range(start='1/1/2000', periods=N_ROWS, freq='h')
})
df.memory_usage(index=False).sum()

np.int64(32000000)

In [8]:
for col in df.columns:
    df[col] =  pd.Categorical(df['product_name'])

df.memory_usage(index=False).sum()

np.int64(4000848)

In [9]:
for col in df.columns:
    df[col] =  pd.Categorical(df['product_category'])

df.memory_usage(index=False).sum()

np.int64(4000848)

In [10]:
print(f"Маємо зниження витрат памʼяті на {round((1-4000848/32000000)*100,2)}% !")

Маємо зниження витрат памʼяті на 87.5% !

7.В цьому завданні кілька пунктів. Треба виконати усі послідовно.   
    7.1. Завантажте дані у pandas dataframe з файла `ecommerce_data.csv`. Обовʼязково при завантаженні вкажіть параметр `encoding = 'ISO-8859-1'`, без нього буде помилка.  
    7.2. Заповніть пропущені значення в колонці CustomerID на -1 та перетворіть тип цієї колонки на str, адже зараз вона типу float, а це не правильний тип даних для ідентифікатора клієнта.  
    7.3. З допомогою бібліотеки sweetviz побудуйте html звіт, який порівнює дані для країни "Germany" і країни "France". У Вас можуть виникнути багато попереджень (Warning), їх рекомендую вимкнути наступним шматком коду   
    
   
    import warnings

    with warnings.catch_warnings(record=True):
        # your code
    
    
   7.4.Напишіть 5 відмінностей для двох зазначених країн на основі побудованого звіту, без виконання додаткового аналізу іншими інструментами.

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('ecommerce_data.csv', encoding = 'ISO-8859-1')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25015 entries, 0 to 25014
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    25015 non-null  object
 1   StockCode    25015 non-null  object
 2   Description  24904 non-null  object
 3   Quantity     25015 non-null  int64
 4   InvoiceDate  25015 non-null  object
 5   UnitPrice    25015 non-null  float64
 6   CustomerID   16056 non-null  float64
 7   Country      25015 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 1.5+ MB

In [15]:
df['CustomerID']

0        17850.0
1        17850.0
2        17850.0
3        17850.0
4        17850.0
          ...
25010        NaN
25011        NaN
25012        NaN
25013        NaN
25014        NaN
Name: CustomerID, Length: 25015, dtype: float64

In [17]:
df['CustomerID'].fillna('-1', inplace = True)
df['CustomerID'].astype(str)

0        17850.0
1        17850.0
2        17850.0
3        17850.0
4        17850.0
          ...
25010         -1
25011         -1
25012         -1
25013         -1
25014         -1
Name: CustomerID, Length: 25015, dtype: object

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25015 entries, 0 to 25014
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    25015 non-null  object
 1   StockCode    25015 non-null  object
 2   Description  24904 non-null  object
 3   Quantity     25015 non-null  int64
 4   InvoiceDate  25015 non-null  object
 5   UnitPrice    25015 non-null  float64
 6   CustomerID   25015 non-null  object
 7   Country      25015 non-null  object
dtypes: float64(1), int64(1), object(6)
memory usage: 1.5+ MB

In [19]:
! pip install sweetviz

Collecting sweetviz
  Downloading sweetviz-2.3.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in /usr/local/lib/python3.12/dist-packages (from sweetviz) (2.2.2)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from sweetviz) (2.0.2)
Requirement already satisfied: matplotlib>=3.1.3 in /usr/local/lib/python3.12/dist-packages (from sweetviz) (3.10.0)
Requirement already satisfied: tqdm>=4.43.0 in /usr/local/lib/python3.12/dist-packages (from sweetviz) (4.67.3)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from sweetviz) (1.16.3)
Requirement already satisfied: jinja2>=2.11.1 in /usr/local/lib/python3.12/dist-packages (from sweetviz) (3.1.6)
Requirement already satisfied: importlib_resources>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from sweetviz) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.11.1->sweetviz) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)
Downloading sweetviz-2.3.3-py3-none-any.whl (15.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.1/15.1 MB 66.2 MB/s eta 0:00:00
Installing collected packages: sweetviz
Successfully installed sweetviz-2.3.3

In [20]:
import sweetviz as sv

In [26]:
germany_df = df[df['Country'] == 'Germany']
france_df = df[df['Country'] == 'France']
compare_report = sv.compare(
    [germany_df, "Germany"],
    [france_df, "France"])

compare_report.show_html('compare_report.html')

                                             |          | [  0%]   00:00 -> (? left)

Report compare_report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

Відмінності між Німечинною та Францією:

- В Німеччині Є багато customerid , що повторюються , припущу що це постійні клієнти з повторними покупками.

- В німечинні в invoicedate помічаємо сплески в певні дні, у Франції багато покупок в різні дні.

- По Invoiceno бачимо , що є великі замовлення в Німеччині та багато поодиноких покупок у Франції.

- Максимальна кількість у Німеччині 100, у Франції 120.

- Максимальна ціна в Німеччині 18, а в Франції 43

8.З допомогою ChatGPT виявіть, чи є та які помилки в наступному коді.  
Попросіть після цього переписати код із дотриманням PEP8. Проаналізуйте результат. Чи справді ChatGPT виправив всі стилістичні помилки? Якщо ні, напишіть йому ще кілька запитів, аби код відповідав вимогам PEP8.  
Вставте фінальну версію коду з чату у ноутбук та запустіть на заданому списку. Має вертатись 50.  
Напишіть, які промпти (інструкції) при зверненні до ChatGPT ви застосували та додайте скріншот(-и) з промптами та відповідями чата.  
Якщо зробили висновки при виконанні цього завдання, то діліться також :)

**ЯК ВСТАВИТИ СКРІНШОТ в Jupyter Notebook** :
1. Створіть нову Markdown клітинку
2. В новоствореній клітинці обираєте в меню Jupyter Notebook Edit -> Insert Image
3. Обираєте картинку
4. В клітинці має зʼявитись текст, який містить картинку. Запустіть клітинку.

Або можна просто перетягнути картинку в Markdown клітинку.

In [9]:
def CalculateVariance(nl):
    sum_list = 0
    for n in nl:
        sum_list = sum_list + n
    mean = sum_list / len(nl)
    sum_squares = 0
    for n in nl:
        sum_squares = sum_squares + n**2
    mean_squares = sum_squares / len(nl)
    return mean_squares

In [12]:
input_list = [75, 80, 85, 90, 95]

In [27]:
import numpy as np

input_list = [75, 80, 85, 90, 95]

variance = np.var(input_list)

print(variance)

50.0

Посилання на промт
https://drive.google.com/drive/folders/1_rWh1qGexlfcVMF50UQa6G34nfhKBEMV?usp=sharing